#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use src\commands\command\ServeCommand;
use src\commands\command\MakeModelCommand;

$application = new Application();

$application->add(new ServeCommand());
$application->add(new MakeModelCommand());

$application->run();